version: "3.8"

services:
  render:
    container_name: render
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - 8080:8080
    volumes:
        - '.:/helpfood-ui'
        - '/helpfood-ui/node_modules'
    environment:
        - CHOKIDAR_USEPOLLING=true 

            
           
            
            