version: '3.8'

services:
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        volumes:
            - '.:/client'
            - '/client/node_modules'
        environment:
            - CHOKIDAR_USEPOLLING=true
    db:
        build:
            context: https://github.com/alp-ex/food-apps-fixtures.git
            dockerfile: Dockerfile
        ports:
            - 3000:3001
